/**
 * @fileOverview Codex Templates
 * 
 * This file contains the templates for the Codex (Legacy Forge).
 */

export interface Template {
    id: string;
    name: string;
    description: string;
    template: string; // a string with placeholders like {{title}}, {{content}}, etc.
}

export const templates: Template[] = [
    {
        id: 'scholarly-white-paper',
        name: 'Scholarly White Paper',
        description: 'A template for generating a scholarly white paper from an artifact.',
        template: `
# {{title}}

**Category:** {{category}}
**Tags:** {{tags}}

## Abstract
{{summary}}

## 1. Introduction
...

## 2. Methodology
...

## 3. Results
...

## 4. Conclusion
...

---
*Generated by Aetherium Nexus Codex*
        `,
    },
    {
        id: 'visual-infographic',
        name: 'Visual Infographic',
        description: 'A template for generating a visual infographic from an artifact.',
        template: `
<div style="border: 1px solid #ccc; padding: 1rem; font-family: sans-serif;">
    <h1 style="font-size: 2rem; margin-bottom: 0.5rem;">{{title}}</h1>
    <div style="margin-bottom: 1rem;">
        <span style="font-weight: bold;">Category:</span> {{category}}
    </div>
    <div style="margin-bottom: 1rem;">
        <span style="font-weight: bold;">Tags:</span> {{tags}}
    </div>
    <p>{{summary}}</p>
</div>
        `,
    },
    {
        id: 'narrative-comic-script',
        name: 'Narrative Comic Script',
        description: 'A template for generating a narrative comic script from an artifact.',
        template: `
**Title:** {{title}}

**Panel 1:**
*   **Description:** ...
*   **Dialogue:** ...

**Panel 2:**
*   **Description:** ...
*   **Dialogue:** ...

**Panel 3:**
*   **Description:** ...
*   **Dialogue:** ...
        `,
    },
];
