'use client';

import React, { useState } from 'react';
import { Idea, NEXUS_IDEAS } from '@/data/nexus-ideas';
import {
    Download,
    CheckCircle2,
    Beaker,
    Scroll,
    Palette,
    GraduationCap,
    ArrowLeft,
    FileText
} from 'lucide-react';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs));
}

export function PublisherView({ onBack }: { onBack: () => void }) {
    const [selectedIdea, setSelectedIdea] = useState<Idea | null>(null);
    const [currentTrack, setCurrentTrack] = useState<keyof Idea['output_tracks']>('scientific');
    const [isCanonized, setIsCanonized] = useState(false);

    const ingestedIdeas = NEXUS_IDEAS.filter(i => i.status === 'ingested');

    const tracks = [
        { id: 'scientific', label: 'Scientific', icon: Beaker },
        { id: 'philosophical', label: 'Philosophical', icon: Scroll },
        { id: 'artistic', label: 'Artistic', icon: Palette },
        { id: 'educational', label: 'Educational', icon: GraduationCap },
    ] as const;

    const handleDownload = () => {
        if (!selectedIdea) return;

        const content = `# ${selectedIdea.title}\n\n## Track: ${currentTrack}\n\n${selectedIdea.output_tracks[currentTrack]}\n\n---\n*Generated by Nexus Multi-Track Publisher*`;
        const blob = new Blob([content], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${selectedIdea.id}_${currentTrack}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const handleCanonize = () => {
        if (!selectedIdea) return;
        setIsCanonized(true);
        // In a real implementation, this would trigger a state update or API call
        setTimeout(() => setIsCanonized(false), 3000);
    };

    return (
        <div className="flex flex-col h-full animate-in fade-in duration-500">
            <header className="flex items-center justify-between mb-8">
                <div>
                    <div className="flex items-center gap-2 mb-1">
                        <button
                            onClick={onBack}
                            className="p-2 hover:bg-white/10 rounded-full transition-colors text-gray-400 hover:text-white"
                        >
                            <ArrowLeft className="w-5 h-5" />
                        </button>
                        <h1 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-emerald-400">
                            Nexus Publisher
                        </h1>
                    </div>
                    <p className="text-gray-500 text-sm ml-11">Multi-Track Synthesis & Canonization Engine</p>
                </div>
            </header>

            <div className="grid grid-cols-1 lg:grid-cols-[350px_1fr] gap-8 flex-1 min-h-0">
                {/* 1. Selection Sidebar */}
                <div className="flex flex-col gap-4 overflow-y-auto pr-2 custom-scrollbar">
                    <h2 className="text-xs font-bold uppercase tracking-widest text-gray-500 mb-2">Ingested Ideas</h2>
                    {ingestedIdeas.length === 0 ? (
                        <div className="p-8 text-center border border-dashed border-white/10 rounded-2xl text-gray-600 italic">
                            No ideas ready for publication.
                        </div>
                    ) : (
                        ingestedIdeas.map((idea) => (
                            <button
                                key={idea.id}
                                onClick={() => setSelectedIdea(idea)}
                                className={cn(
                                    "p-4 rounded-2xl text-left transition-all border group",
                                    selectedIdea?.id === idea.id
                                        ? "bg-blue-600/10 border-blue-500/50"
                                        : "bg-gray-900/40 border-white/5 hover:border-white/20 hover:bg-white/5"
                                )}
                            >
                                <h4 className={cn(
                                    "font-semibold mb-1 transition-colors",
                                    selectedIdea?.id === idea.id ? "text-blue-400" : "text-gray-200"
                                )}>
                                    {idea.title}
                                </h4>
                                <p className="text-xs text-gray-500 line-clamp-1">{idea.description}</p>
                            </button>
                        ))
                    )}
                </div>

                {/* 2. Synthesis Main Area */}
                <div className="flex flex-col h-full">
                    {selectedIdea ? (
                        <div className="flex flex-col h-full bg-gray-900/40 backdrop-blur-xl border border-white/10 rounded-3xl overflow-hidden p-8 animate-in slide-in-from-right-8 duration-500">
                            <div className="flex flex-wrap items-center justify-between gap-4 mb-8">
                                <h3 className="text-2xl font-bold text-white">{selectedIdea.title}</h3>
                                <div className="flex bg-gray-950/50 p-1 rounded-xl border border-white/10">
                                    {tracks.map((track) => (
                                        <button
                                            key={track.id}
                                            onClick={() => setCurrentTrack(track.id)}
                                            className={cn(
                                                "flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all",
                                                currentTrack === track.id
                                                    ? "bg-blue-600 text-white shadow-lg shadow-blue-900/20"
                                                    : "text-gray-500 hover:text-gray-300"
                                            )}
                                        >
                                            <track.icon className="w-4 h-4" />
                                            <span className="hidden sm:inline">{track.label}</span>
                                        </button>
                                    ))}
                                </div>
                            </div>

                            <div className="flex-1 min-h-0 flex flex-col mb-8">
                                <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-gray-500 mb-4">
                                    <FileText className="w-3 h-3" />
                                    Output Preview
                                </div>
                                <div className="flex-1 bg-gray-950/50 border border-white/5 rounded-2xl p-6 overflow-y-auto custom-scrollbar font-mono text-sm leading-relaxed text-gray-300">
                                    {selectedIdea.output_tracks[currentTrack]}
                                </div>
                            </div>

                            <div className="flex items-center justify-end gap-4 pt-6 border-t border-white/5">
                                <button
                                    onClick={handleDownload}
                                    className="flex items-center gap-2 px-6 py-3 rounded-xl bg-white/5 hover:bg-white/10 text-white font-medium transition-all"
                                >
                                    <Download className="w-4 h-4" />
                                    Download as .md
                                </button>
                                <button
                                    onClick={handleCanonize}
                                    disabled={isCanonized}
                                    className={cn(
                                        "flex items-center gap-2 px-8 py-3 rounded-xl font-bold transition-all",
                                        isCanonized
                                            ? "bg-emerald-500 text-white"
                                            : "bg-gradient-to-r from-blue-600 to-emerald-600 text-white hover:scale-[1.02] active:scale-95 shadow-lg shadow-blue-900/20"
                                    )}
                                >
                                    {isCanonized ? (
                                        <>
                                            <CheckCircle2 className="w-5 h-5" />
                                            Canonized!
                                        </>
                                    ) : (
                                        'Canonize for Baseline'
                                    )}
                                </button>
                            </div>
                        </div>
                    ) : (
                        <div className="flex flex-col items-center justify-center flex-1 bg-gray-900/20 border border-dashed border-white/10 rounded-3xl text-gray-600">
                            <Layers className="w-12 h-12 mb-4 opacity-20" />
                            <p className="text-lg">Select an idea from the sidebar to begin synthesis.</p>
                            <p className="text-sm">Only ideas in the "Ingested" state can be published.</p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}

const Layers = ({ className }: { className?: string }) => (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        className={className}
    >
        <path d="m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z" />
        <path d="m2.6 12.18 8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9" />
        <path d="m2.6 17.18 8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9" />
    </svg>
);
